@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System_Boundary(c1, "PAPI") {
Container(reviewSystem, "Review/Feedback", "Review system", "Configure process and promotions")
' Performance
Container(billingSystem, "Compensation", "Compensation system", "Configure billing information")
' Billing
' Payroll
Container(personSystem, "Person system", "Personal system", "Configure static personal informations")
' People
' Inventory
Container(skillSystem, "Skill", "Skill system", "Configure skill information")
' Staffing
Container(jobSystem, "Job", "Job system", "Configure job related metadata. This system changes a lot depending at the company needs")
' Staffing
' People
' Billing
}

@enduml